
# Task 1 
#create a Class Rectangle Here we create the class name Rectangle .
# A rectangle has a Widht and Lenght
# we inital the lenght and width with a default value 1
class Rectangle(object):
    def __init__(self):
      pass
   

# we can now create rectangles example Rect1 with , Rect2 and so on
Rect1 = Rectangle()
Rect2 = Rectangle()

#print the memory of the Rect1
print(hex(id(Rect1)))


#Task1
class Rectangle(object):
    def __init__(self,colour):
      print(hex(id(self)))
    
	pass
	
	#=================

class Employee:
    pass

john = Employee()  # Create an empty employee record

# Fill the fields of the record
john.name = 'John Doe'
john.dept = 'computer lab'
john.salary = 1000


#===================


# Task 3 create a Class Rectangle Here we create the class name Rectangle with attribute colour and method description.
# A rectangle has a Widht and Lenght
# we inital the lenght and width with a default value 1
class Rectangle(object):
    
    def __init__(self,colour,side1,side2):
      hex(id(self))  # to get the address in memory
      self.colour = colour
      self.side1= side1 # add two more attribute side
      self.side2= side2
    
    def description(self):
      print("The colour of the rectangle is : " + self.colour)
      print("The first side is  : " + str(self.side1)) #str to convert int to string as we are printing a text here
      print("The second side is  : " + str(self.side2))
    

# we can now create rectangles example Rect1 , Rect2 and so on

Rect1 = Rectangle('yellow',2,2)
Rect2 = Rectangle('Red',3,3)

print(Rect1)
print(Rect2)
Rect1.description()
Rect2.description()

#================================


# Task 4 create a Class Rectangle Here we create the class name Rectangle with attribute colour and method description.
# count how many time we create a rectangle
# we inital the lenght and width with a default value 1
class Rectangle(object):
    
    NumberofRectangle_object = 0 # a variable to get the number of Rectangle create

    def __init__(self,colour,side1,side2,x,y):
      hex(id(self))  # to get the address in memory
      Rectangle.NumberofRectangle_object  += 1 # Increment by 1 when new object is created
      self.counterclass =Rectangle.NumberofRectangle_object

      self.colour = colour
      self.side1= side1 # add two more attribute side
      self.side2= side2
      self.x = x
      self.y = y
    
    def description(self):
      print("The colour of the rectangle is : " + self.colour)
      print("The first side is  : " + str(self.side1) + " mm") #str to convert int to string as we are printing a text here
      print("The second side is  : " + str(self.side2) + " mm" )
      print("The number of rectangles generated by the Rectangle class is " + str(self.counterclass))
      print("The bottom left coordinates of the rectangle is "+ "[" + str(self.x) +","+ str(self.y) +"]")
    
    def expand(self):
      self.side1= side1 # add two more attribute side
      self.side2= side2

    def translate(self,x_direction,y_direction):
      self.x = self.x + x_direction
      self.y = self.y + y_direction

    def changeColour(self,newColour):
      self.colour = newColour


# we can now create rectangles example Rect1 , Rect2 and so on

Rect1 = Rectangle('yellow',2,2,3,4)
print(Rect1)
Rect1.description()
Rect2 = Rectangle('Red',1,1,2,4)
Rect2.description()

Rect2.expand()
Rect2.translate(4,5)
Rect2.changeColour('orange')
Rect2.description()

=####

Reworks 3


# Task 3 create a Class Rectangle Here we create the class name Rectangle with attribute colour and method description.
# count how many time we create a rectangle
# we inital the lenght and width with a default value 1
class Rectangle(object):
    
    NumberofRectangle_object = 0 # a variable to get the number of Rectangle create

    def __init__(self,colour,side1,side2,x,y):
      hex(id(self))  # to get the address in memory
      Rectangle.NumberofRectangle_object  += 1 # Increment by 1 when new object is created
      self.counterclass =Rectangle.NumberofRectangle_object

      self.colour = colour
      self.side1= side1 # add two more attribute side
      self.side2= side2
      self.x = x
      self.y = y
    
    def description(self):
      print("The colour of the rectangle is : " + self.colour)
      print("The first side is  : " + str(self.side1) + " mm") #str to convert int to string as we are printing a text here
      print("The second side is  : " + str(self.side2) + " mm" )
   #   print("The number of rectangles generated by the Rectangle class is " + str(self.counterclass))
    #  print("The bottom left coordinates of the rectangle is "+ "[" + str(self.x) +","+ str(self.y) +"]")
    
    def expand(self):
      self.side1= self.side1 + 2 # add two more attribute side
      self.side2= self.side1 + 3

    def changeColour(self,newColour):
      self.colour = newColour


# we can now create rectangles example Rect1 , Rect2 and so on

Rect1 = Rectangle('yellow',2,2,3,4)
print(Rect1)
Rect1.description()
Rect2 = Rectangle('Red',1,1,2,4)
Rect2.description()

Rect2.expand()
Rect2.description()

Rect2.changeColour('orange')
Rect2.description()




Task4>


# Task 4 create a Class Rectangle Here we create the class name Rectangle with attribute colour and method description.
# count how many time we create a rectangle
# we inital the lenght and width with a default value 1
class Rectangle(object):
    
    NumberofRectangle_object = 0 # a variable to get the number of Rectangle create

    def __init__(self,colour,side1,side2,x,y):
      hex(id(self))  # to get the address in memory
      Rectangle.NumberofRectangle_object  += 1 # Increment by 1 when new object is created
      self.counterclass =Rectangle.NumberofRectangle_object

      self.colour = colour
      self.side1= side1 # add two more attribute side
      self.side2= side2
      self.x = x
      self.y = y
    
    def description(self):
      print("The colour of the rectangle is : " + self.colour)
      print("The first side is  : " + str(self.side1) + " mm") #str to convert int to string as we are printing a text here
      print("The second side is  : " + str(self.side2) + " mm" )
      print("The number of rectangles generated by the Rectangle class is " + str(self.counterclass))
      print("The bottom left coordinates of the rectangle is "+ "[" + str(self.x) +","+ str(self.y) +"]")
    
    def expand(self):
      self.side1= self.side1 + 2 # add two more attribute side
      self.side2= self.side2 + 3

    def changeColour(self,newColour):
      self.colour = newColour

    def translate(self,x_direction,y_direction):
      self.x = self.x + x_direction
      self.y = self.y + y_direction  


# we can now create rectangles example Rect1 , Rect2 and so on

Rect1 = Rectangle('yellow',2,2,3,4)
print(Rect1)
Rect1.description()
Rect2 = Rectangle('Red',1,1,2,4)
Rect2.description()

Rect2.expand()
Rect2.translate(4,5)

Rect2.changeColour('orange')
Rect2.description()
